### ISSUE TITLE
Error accessing `X` in `HDF5AnnData` when empty

### ISSUE THREAD

**Issue by lazappi** [scverse/anndataR#164]
If the `X` slot in an `HDF5AnnData` is empty, trying to access it gives this error:

```r
Error in rhdf5::h5readAttributes(file, name) : 
  Object /X does not exist in this HDF5 file.
```

Needs to be handled in some way. Should probably be filled in the same way as Python when creating a new H5AD file.

**Comment by rcannood** [comment]
This has been fixed in the meantime!
