### ISSUE TITLE
Share validation functions?

### ISSUE THREAD

**Issue by lazappi** [scverse/anndataR#52]
Could the validation functions in `InMemoryAnnData` be moved to `AbstractAnnData` or somewhere else where they can be reused across classes? I feel like I was about to implement essentially the same thing for `HDF5AnnData` so it would be good to avoid duplicating things if we can.

**Comment by rcannood** [comment]
:+1:!

If, for some reason, some of the validation functions are not applicable for one of the classes, we can still override it.

**Comment by rcannood** [comment]
validation functions were moved to validation functions as part of #70
