### ISSUE TITLE
Implement `from_Seurat` and `to_Seurat`

### ISSUE THREAD

**Issue by rcannood** [scverse/anndataR#60]

**Comment by bschilder** [comment]
## `from_Seurat ` strategy
- [ ] Only support single-assays when converting to "AbstractAnnData". 
- [ ] When a Seurat object has >1 assay, tell the user the Default assay is being used.
- [ ] Also allow the user to select which assay they want to use.
- [ ] Turn each matrix element within the selected assay into layers (`counts`, `data`, `scaled.data`).
- [ ] Set `X` as `counts` matrix element by default, as you can always normalise/manipulate the data from afterwards. However, allow the user the option of setting `X=NULL`

**Comment by rcannood** [comment]
Sounds good, thanks!

**Comment by csangara** [comment]
@bschilder @rcannood By the way, I will not have time to work on this anymore before the deadline. You can see what I've done so far in the `issue-60-from-seurat-obsm-varm` branch. I didn't get to test it very much yet so some parts will probably not work.

**Comment by rcannood** [comment]
Fixed by #183
