### ISSUE TITLE
Make obs and var optional, make obs_names and var_names required

### ISSUE THREAD

**Issue by rcannood** [scverse/anndataR#76]
At the moment, we require that `obs` and `var` are passed to the InMemoryAnnData and HDF5AnnData, while other slots are optional.

However, looking at what happens when I create an empty AnnData in Python, it's actually the `obs_names` and the `var_names` that are required, and not `obs` and `var` -- I guess.

```python
import anndata as ad
adata = ad.AnnData(shape=[10, 20])
adata.write_h5ad("empty.h5ad")
```

```r
file <- rhdf5::H5Fopen("empty.h5ad")
rhdf5::h5ls(file)
```

      group   name       otype dclass dim
    0     / layers   H5I_GROUP           
    1     /    obs   H5I_GROUP           
    2  /obs _index H5I_DATASET STRING  10
    3     /   obsm   H5I_GROUP           
    4     /   obsp   H5I_GROUP           
    5     /    uns   H5I_GROUP           
    6     /    var   H5I_GROUP           
    7  /var _index H5I_DATASET STRING  20
    8     /   varm   H5I_GROUP           
    9     /   varp   H5I_GROUP

As such; I propose altering the code of `InMemoryAnnData` and `HDF5AnnData` require the `obs_names` and the `var_names` to be passed, not the `obs` and the `var`.

**Comment by rcannood** [comment]
I agree this is very practical, but given #73 we can't add the obs_names to the obs as rownames or to the X as rownames because the obs_names might be integers instead of characters.

**Comment by rcannood** [comment]
> What does Python anndata put in obs_names/var_names when you just set the shape?

This is what's shown in the original message, no?

**Comment by lazappi** [comment]
> > What does Python anndata put in obs_names/var_names when you just set the shape?
> 
> This is what's shown in the original message, no?

Not entirely, but I could just check myself rather than asking you silly questions 😸
