### ISSUE TITLE
Add rworkflows

### ISSUE THREAD

**Issue by bschilder** [scverse/anndataR#94]
I'll be working on implementing CI via `rworkflows`, which should help streamline some of the CI workflow scripts implemented currently, plus add new things like Docker container generation.

**Comment by bschilder** [comment]
Added here:
https://github.com/bschilder/anndataR/tree/rworkflows/.github/workflows

Testing it out now.

**Comment by rcannood** [comment]
I don't think we have any immediate plans to switch to rworkflows for now. Sorry @bschilder !
