### ISSUE TITLE
Automatically setup conda env

### ISSUE THREAD

**Issue by bschilder** [scverse/anndataR#97]
Add a function that auto-installs `miniconda` and then sets up a `conda` env to .
This would only be run when:
1) an `anndataR` function (or unit test) requires reticulate.
2) the conda env is not already present.

Could use either `reticulate` or `basilisk` for this.

**Comment by bschilder** [comment]
Created new function: `setup_conda`

https://github.com/bschilder/anndataR/blob/rworkflows/R/setup_conda.R

**Comment by lazappi** [comment]
This should use **{basilisk}** for Bioconductor compatibility. I'm not 100% sure we want to mess around with Python environments in this package though.

**Comment by rcannood** [comment]
@lazappi Agreed :)
